postgresql:
  image: orchardup/postgresql:latest
  environment:
    - POSTGRESQL_USER=sonar
    - POSTGRESQL_PASS=xaexohquaetiesoo
    - POSTGRESQL_DB=sonar
sonarqube:
  image: harbur/sonarqube:5.0
  links:
    - postgresql:db
  environment:
    - DB_USER=sonar
    - DB_PASS=xaexohquaetiesoo
    - DB_NAME=sonar
    - VIRTUAL_HOST
    - VIRTUAL_PORT=9000
  ports:
    - "9000"
    - "443"
