web:
  image: wordpress:4.1.0
  ports:
    - "80"
  links:
    - mysql:mysql
  environment:
    WORDPRESS_DB_PASSWORD: mypwd
mysql:
  image: orchardup/mysql:latest
  environment:
    MYSQL_DATABASE: wordpress
    MYSQL_ROOT_PASSWORD: mypwd

